version: '3.9'

services:
    app:
        build:
            context: .
            dockerfile: development/Dockerfile
        container_name: app-dev
        volumes:
            - .:/app
            - /app/node_modules
        ports:
            - '3000:3000'
        environment:
            - ENV=development
            - CHOKIDAR_USEPOLLING=true
        command: pnpm run dev
