version: '3.9'

services:
    app:
        image: mstummesalma/backend-starter-toolkit:latest
        container_name: backend-starter-toolkit
        restart: always
        ports:
            - '80:3000'
        environment:
            - ENV=production
        volumes:
            - ./logs:/app/logs
